name: Infraestructure Deployment
on:
  push:
    branches: ["main"]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
jobs:
  deploy:
    name: Terraform settings
    runs-on: ubuntu-latest
    steps: 
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Terraform init
      run: terraform init -backend-config="sas_token=${{ secrets.SAS_TOKEN }}"
      working-directory: ./

    - name: Terraform validate
      run: terraform validate
      working-directory: ./

    - name: Terraform plan
      run: terraform plan -var-file terraform.tfvars -out-plan.out
      working-directory: ./

    - name: Terraform apply
      run: terraform apply -var-file terraform.tfvars -auto-approve
      working-directory: ./

      
    

      
